language: php

sudo: false

cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache/files

branches:
  only:
    - master
    - /^\d+\.\d+$/

matrix:
  fast_finish: true
  include:
    # Symfony 3 
    - php: 7.0
    # Symfony 4
    - php: 7.1
    - php: 7.2
    # Symfony 5 LTS
    - php: 7.2
    - php: 7.4
    - php: 8.0
      env: SYMFONY_LTS='^5'
    # development dependencies
    - php: 7.2
      env: DEPENDENCIES='dev'
  allow_failures:
    - php: 7.2
      env: DEPENDENCIES='dev'

before_install:
  - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi
  - if [ "$DEPENDENCIES" != "" ]; then composer config minimum-stability $DEPENDENCIES; fi
  - if [ "$SYMFONY_LTS" != "" ]; then composer require --dev --no-update symfony/lts=$SYMFONY_LTS; fi

install:
  - composer update $COMPOSER_FLAGS --prefer-dist
  - ./phpunit install

script: ./phpunit
